/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { HeaderNavItem } from "./model/HeaderNavMenu";
export { HeaderNavItem } from "./model/HeaderNavMenu";
export namespace Components {
    interface DesignTokenManagement {
        "json": string;
    }
    interface SandboxMainContent {
    }
    interface UswdsAccordion {
        "accordionType": 'borderless' | 'bordered' | 'multiselectable';
    }
    interface UswdsAccordionItem {
        "expanded": boolean;
        "header": string;
    }
    interface UswdsExtendedHeader {
    }
    interface UswdsHeader {
        "enableSearch": boolean;
        "headerTitle": string;
        "navItems": HeaderNavItem[];
    }
    interface UswdsModal {
    }
    interface UswdsSideNav {
        "region": string;
    }
    interface UswdsSideNavItem {
    }
    interface UswdsSideNavSubList {
    }
}
declare global {
    interface HTMLDesignTokenManagementElement extends Components.DesignTokenManagement, HTMLStencilElement {
    }
    var HTMLDesignTokenManagementElement: {
        prototype: HTMLDesignTokenManagementElement;
        new (): HTMLDesignTokenManagementElement;
    };
    interface HTMLSandboxMainContentElement extends Components.SandboxMainContent, HTMLStencilElement {
    }
    var HTMLSandboxMainContentElement: {
        prototype: HTMLSandboxMainContentElement;
        new (): HTMLSandboxMainContentElement;
    };
    interface HTMLUswdsAccordionElement extends Components.UswdsAccordion, HTMLStencilElement {
    }
    var HTMLUswdsAccordionElement: {
        prototype: HTMLUswdsAccordionElement;
        new (): HTMLUswdsAccordionElement;
    };
    interface HTMLUswdsAccordionItemElement extends Components.UswdsAccordionItem, HTMLStencilElement {
    }
    var HTMLUswdsAccordionItemElement: {
        prototype: HTMLUswdsAccordionItemElement;
        new (): HTMLUswdsAccordionItemElement;
    };
    interface HTMLUswdsExtendedHeaderElement extends Components.UswdsExtendedHeader, HTMLStencilElement {
    }
    var HTMLUswdsExtendedHeaderElement: {
        prototype: HTMLUswdsExtendedHeaderElement;
        new (): HTMLUswdsExtendedHeaderElement;
    };
    interface HTMLUswdsHeaderElement extends Components.UswdsHeader, HTMLStencilElement {
    }
    var HTMLUswdsHeaderElement: {
        prototype: HTMLUswdsHeaderElement;
        new (): HTMLUswdsHeaderElement;
    };
    interface HTMLUswdsModalElement extends Components.UswdsModal, HTMLStencilElement {
    }
    var HTMLUswdsModalElement: {
        prototype: HTMLUswdsModalElement;
        new (): HTMLUswdsModalElement;
    };
    interface HTMLUswdsSideNavElement extends Components.UswdsSideNav, HTMLStencilElement {
    }
    var HTMLUswdsSideNavElement: {
        prototype: HTMLUswdsSideNavElement;
        new (): HTMLUswdsSideNavElement;
    };
    interface HTMLUswdsSideNavItemElement extends Components.UswdsSideNavItem, HTMLStencilElement {
    }
    var HTMLUswdsSideNavItemElement: {
        prototype: HTMLUswdsSideNavItemElement;
        new (): HTMLUswdsSideNavItemElement;
    };
    interface HTMLUswdsSideNavSubListElement extends Components.UswdsSideNavSubList, HTMLStencilElement {
    }
    var HTMLUswdsSideNavSubListElement: {
        prototype: HTMLUswdsSideNavSubListElement;
        new (): HTMLUswdsSideNavSubListElement;
    };
    interface HTMLElementTagNameMap {
        "design-token-management": HTMLDesignTokenManagementElement;
        "sandbox-main-content": HTMLSandboxMainContentElement;
        "uswds-accordion": HTMLUswdsAccordionElement;
        "uswds-accordion-item": HTMLUswdsAccordionItemElement;
        "uswds-extended-header": HTMLUswdsExtendedHeaderElement;
        "uswds-header": HTMLUswdsHeaderElement;
        "uswds-modal": HTMLUswdsModalElement;
        "uswds-side-nav": HTMLUswdsSideNavElement;
        "uswds-side-nav-item": HTMLUswdsSideNavItemElement;
        "uswds-side-nav-sub-list": HTMLUswdsSideNavSubListElement;
    }
}
declare namespace LocalJSX {
    interface DesignTokenManagement {
        "json"?: string;
    }
    interface SandboxMainContent {
    }
    interface UswdsAccordion {
        "accordionType"?: 'borderless' | 'bordered' | 'multiselectable';
    }
    interface UswdsAccordionItem {
        "expanded"?: boolean;
        "header"?: string;
    }
    interface UswdsExtendedHeader {
    }
    interface UswdsHeader {
        "enableSearch"?: boolean;
        "headerTitle"?: string;
        "navItems"?: HeaderNavItem[];
    }
    interface UswdsModal {
    }
    interface UswdsSideNav {
        "region"?: string;
    }
    interface UswdsSideNavItem {
    }
    interface UswdsSideNavSubList {
    }
    interface IntrinsicElements {
        "design-token-management": DesignTokenManagement;
        "sandbox-main-content": SandboxMainContent;
        "uswds-accordion": UswdsAccordion;
        "uswds-accordion-item": UswdsAccordionItem;
        "uswds-extended-header": UswdsExtendedHeader;
        "uswds-header": UswdsHeader;
        "uswds-modal": UswdsModal;
        "uswds-side-nav": UswdsSideNav;
        "uswds-side-nav-item": UswdsSideNavItem;
        "uswds-side-nav-sub-list": UswdsSideNavSubList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "design-token-management": LocalJSX.DesignTokenManagement & JSXBase.HTMLAttributes<HTMLDesignTokenManagementElement>;
            "sandbox-main-content": LocalJSX.SandboxMainContent & JSXBase.HTMLAttributes<HTMLSandboxMainContentElement>;
            "uswds-accordion": LocalJSX.UswdsAccordion & JSXBase.HTMLAttributes<HTMLUswdsAccordionElement>;
            "uswds-accordion-item": LocalJSX.UswdsAccordionItem & JSXBase.HTMLAttributes<HTMLUswdsAccordionItemElement>;
            "uswds-extended-header": LocalJSX.UswdsExtendedHeader & JSXBase.HTMLAttributes<HTMLUswdsExtendedHeaderElement>;
            "uswds-header": LocalJSX.UswdsHeader & JSXBase.HTMLAttributes<HTMLUswdsHeaderElement>;
            "uswds-modal": LocalJSX.UswdsModal & JSXBase.HTMLAttributes<HTMLUswdsModalElement>;
            "uswds-side-nav": LocalJSX.UswdsSideNav & JSXBase.HTMLAttributes<HTMLUswdsSideNavElement>;
            "uswds-side-nav-item": LocalJSX.UswdsSideNavItem & JSXBase.HTMLAttributes<HTMLUswdsSideNavItemElement>;
            "uswds-side-nav-sub-list": LocalJSX.UswdsSideNavSubList & JSXBase.HTMLAttributes<HTMLUswdsSideNavSubListElement>;
        }
    }
}
