/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { HeaderNavItem } from "./model/HeaderNavMenu";
export { HeaderNavItem } from "./model/HeaderNavMenu";
export namespace Components {
    interface GithubConnector {
    }
    interface SandboxMainContent {
    }
    interface UswdsExtendedHeader {
    }
    interface UswdsHeader {
        "enableSearch": boolean;
        "headerTitle": string;
        "navItems": HeaderNavItem[];
    }
    interface UswdsSideNav {
        "region": string;
    }
    interface UswdsSideNavItem {
    }
    interface UswdsSideNavSubList {
    }
}
declare global {
    interface HTMLGithubConnectorElement extends Components.GithubConnector, HTMLStencilElement {
    }
    var HTMLGithubConnectorElement: {
        prototype: HTMLGithubConnectorElement;
        new (): HTMLGithubConnectorElement;
    };
    interface HTMLSandboxMainContentElement extends Components.SandboxMainContent, HTMLStencilElement {
    }
    var HTMLSandboxMainContentElement: {
        prototype: HTMLSandboxMainContentElement;
        new (): HTMLSandboxMainContentElement;
    };
    interface HTMLUswdsExtendedHeaderElement extends Components.UswdsExtendedHeader, HTMLStencilElement {
    }
    var HTMLUswdsExtendedHeaderElement: {
        prototype: HTMLUswdsExtendedHeaderElement;
        new (): HTMLUswdsExtendedHeaderElement;
    };
    interface HTMLUswdsHeaderElement extends Components.UswdsHeader, HTMLStencilElement {
    }
    var HTMLUswdsHeaderElement: {
        prototype: HTMLUswdsHeaderElement;
        new (): HTMLUswdsHeaderElement;
    };
    interface HTMLUswdsSideNavElement extends Components.UswdsSideNav, HTMLStencilElement {
    }
    var HTMLUswdsSideNavElement: {
        prototype: HTMLUswdsSideNavElement;
        new (): HTMLUswdsSideNavElement;
    };
    interface HTMLUswdsSideNavItemElement extends Components.UswdsSideNavItem, HTMLStencilElement {
    }
    var HTMLUswdsSideNavItemElement: {
        prototype: HTMLUswdsSideNavItemElement;
        new (): HTMLUswdsSideNavItemElement;
    };
    interface HTMLUswdsSideNavSubListElement extends Components.UswdsSideNavSubList, HTMLStencilElement {
    }
    var HTMLUswdsSideNavSubListElement: {
        prototype: HTMLUswdsSideNavSubListElement;
        new (): HTMLUswdsSideNavSubListElement;
    };
    interface HTMLElementTagNameMap {
        "github-connector": HTMLGithubConnectorElement;
        "sandbox-main-content": HTMLSandboxMainContentElement;
        "uswds-extended-header": HTMLUswdsExtendedHeaderElement;
        "uswds-header": HTMLUswdsHeaderElement;
        "uswds-side-nav": HTMLUswdsSideNavElement;
        "uswds-side-nav-item": HTMLUswdsSideNavItemElement;
        "uswds-side-nav-sub-list": HTMLUswdsSideNavSubListElement;
    }
}
declare namespace LocalJSX {
    interface GithubConnector {
    }
    interface SandboxMainContent {
    }
    interface UswdsExtendedHeader {
    }
    interface UswdsHeader {
        "enableSearch"?: boolean;
        "headerTitle"?: string;
        "navItems"?: HeaderNavItem[];
    }
    interface UswdsSideNav {
        "region"?: string;
    }
    interface UswdsSideNavItem {
    }
    interface UswdsSideNavSubList {
    }
    interface IntrinsicElements {
        "github-connector": GithubConnector;
        "sandbox-main-content": SandboxMainContent;
        "uswds-extended-header": UswdsExtendedHeader;
        "uswds-header": UswdsHeader;
        "uswds-side-nav": UswdsSideNav;
        "uswds-side-nav-item": UswdsSideNavItem;
        "uswds-side-nav-sub-list": UswdsSideNavSubList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "github-connector": LocalJSX.GithubConnector & JSXBase.HTMLAttributes<HTMLGithubConnectorElement>;
            "sandbox-main-content": LocalJSX.SandboxMainContent & JSXBase.HTMLAttributes<HTMLSandboxMainContentElement>;
            "uswds-extended-header": LocalJSX.UswdsExtendedHeader & JSXBase.HTMLAttributes<HTMLUswdsExtendedHeaderElement>;
            "uswds-header": LocalJSX.UswdsHeader & JSXBase.HTMLAttributes<HTMLUswdsHeaderElement>;
            "uswds-side-nav": LocalJSX.UswdsSideNav & JSXBase.HTMLAttributes<HTMLUswdsSideNavElement>;
            "uswds-side-nav-item": LocalJSX.UswdsSideNavItem & JSXBase.HTMLAttributes<HTMLUswdsSideNavItemElement>;
            "uswds-side-nav-sub-list": LocalJSX.UswdsSideNavSubList & JSXBase.HTMLAttributes<HTMLUswdsSideNavSubListElement>;
        }
    }
}
